"use strict";

const state={parameters:window.BRAIN_HQ_INITIAL,sizing:null,controllers:[],dispatch:null,human:null,humanTrace:[],live:null,benchmarkJob:null,shadowJob:null};
const $=id=>document.getElementById(id);
const number=(value,digits=2)=>Number(value||0).toLocaleString(undefined,{maximumFractionDigits:digits});
async function api(url,options={}){const response=await fetch(url,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||`${response.status} ${response.statusText}`);return payload;}
function formObject(form){return Object.fromEntries([...new FormData(form).entries()].map(([key,value])=>[key,value]));}
function metrics(target,rows){target.innerHTML=rows.map(([label,value])=>`<div class="metric"><span>${label}</span><b>${value}</b></div>`).join("");}
function table(target,rows,columns){if(!rows.length){target.innerHTML="<p>No rows yet.</p>";return;}target.innerHTML=`<table><thead><tr>${columns.map(column=>`<th>${column[1]}</th>`).join("")}</tr></thead><tbody>${rows.map(row=>`<tr>${columns.map(column=>`<td>${column[2]?column[2](row[column[0]],row):row[column[0]]??""}</td>`).join("")}</tr>`).join("")}</tbody></table>`;}
function roster(target,controllers,prefix,defaults=["brain1","brain2"]){target.innerHTML=controllers.filter(row=>!row.error).map(row=>`<label><input type="checkbox" data-roster="${prefix}" value="${row.id}" ${defaults.includes(row.id)?"checked":""}>${row.display_name||row.name}</label>`).join("");}
function selected(prefix){return [...document.querySelectorAll(`[data-roster="${prefix}"]:checked`)].map(input=>input.value);}
function canvasContext(id){const canvas=$(id);const ratio=devicePixelRatio||1;const width=Math.max(320,canvas.clientWidth);const height=Math.max(220,canvas.clientHeight);canvas.width=width*ratio;canvas.height=height*ratio;const context=canvas.getContext("2d");context.setTransform(ratio,0,0,ratio,0,0);context.clearRect(0,0,width,height);return{context,width,height};}
function plot(id,series){const {context,width,height}=canvasContext(id);const pad={left:52,right:18,top:22,bottom:32};const values=series.flatMap(row=>row.values).filter(Number.isFinite);if(!values.length){context.fillStyle="#94aebe";context.fillText("No trace",20,30);return;}const low=Math.min(...values),high=Math.max(...values),span=Math.max(1e-9,high-low),count=Math.max(...series.map(row=>row.values.length),2);context.strokeStyle="#294258";for(let i=0;i<=4;i++){const y=pad.top+(height-pad.top-pad.bottom)*i/4;context.beginPath();context.moveTo(pad.left,y);context.lineTo(width-pad.right,y);context.stroke();}series.forEach(row=>{context.strokeStyle=row.color;context.lineWidth=2;context.beginPath();row.values.forEach((value,index)=>{const x=pad.left+(width-pad.left-pad.right)*index/(count-1),y=pad.top+(height-pad.top-pad.bottom)*(1-(value-low)/span);index?context.lineTo(x,y):context.moveTo(x,y);});context.stroke();});context.fillStyle="#94aebe";context.fillText(number(high),4,pad.top+4);context.fillText(number(low),4,height-pad.bottom);series.forEach((row,index)=>{context.fillStyle=row.color;context.fillRect(pad.left+index*150,6,10,3);context.fillText(row.label,pad.left+14+index*150,11);});}

document.querySelectorAll(".tab").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".tab,.panel").forEach(item=>item.classList.remove("active"));button.classList.add("active");$(`tab-${button.dataset.tab}`).classList.add("active");}));

async function loadSizing(){const payload=await api("/api/sizing");state.sizing=payload.benchmark;const summary=state.sizing.summary;metrics($("sizing-summary"),[["Days",summary.day_count],["Raw grid kWh",number(summary.total_grid_kWh)],["Raw peak kW",number(summary.peak_grid_kW)],["Energy cost",number(summary.energy_cost_vnd,0)+" VND"],["Demand cost",number(summary.demand_charge_vnd,0)+" VND"]]);$("sizing-day").innerHTML=state.sizing.days.map((day,index)=>`<option value="${index}">${day.date_iso||`Day ${day.day_index}`}</option>`).join("");drawSizing();}
function drawSizing(){const day=state.sizing?.days?.[Number($("sizing-day").value||0)];if(day)plot("sizing-chart",[{label:"Load",color:"#fb923c",values:day.load},{label:"PV",color:"#4ade80",values:day.pv},{label:"Grid",color:"#38bdf8",values:day.grid}]);}
$("sizing-day").addEventListener("change",drawSizing);
$("save-settings").addEventListener("click",async()=>{try{const payload=formObject($("settings-form"));payload.billing_sunday=$("settings-form").elements.billing_sunday.checked;const result=await api("/api/parameters",{method:"POST",body:JSON.stringify(payload)});state.parameters=result.parameters;await loadSizing();}catch(error){alert(error.message);}});
$("oracle-run").addEventListener("click",async()=>{try{$("oracle-output").textContent="Solving optional ceiling...";const payload=await api("/candidate-oracle/0?force=1");$("oracle-output").textContent=JSON.stringify(payload.candidate.oracle.summary||payload.candidate.oracle,null,2);}catch(error){$("oracle-output").textContent=error.message;}});

async function loadTraining(){const [datasets,checkpoints]=await Promise.all([api("/api/training/datasets"),api("/api/training/checkpoints")]);$("training-dataset").innerHTML=datasets.filter(row=>row.status==="ok").map(row=>`<option value="${row.id}">${row.source} (${row.n_days} days, ${row.res_min}m)</option>`).join("");$("training-resume").innerHTML='<option value="">Fresh run</option>'+checkpoints.resume.map(name=>`<option>${name}</option>`).join("");table($("training-checkpoints"),checkpoints.deployments,[["display_name","Checkpoint"],["algo","Algorithm"],["error","Status",value=>value||"ready"]]);}
$("training-refresh").addEventListener("click",loadTraining);
$("training-start").addEventListener("click",async()=>{try{const result=await api("/api/training/start",{method:"POST",body:JSON.stringify(formObject($("training-form")))});$("training-log").textContent=`Job ${result.job_id} launched. Heavy training belongs on the configured machine.`;const points=[],events=new EventSource(`/api/training/jobs/${result.job_id}/events`);events.onmessage=event=>{try{const row=JSON.parse(event.data);if(row.type==="validation"){points.push(row);plot("training-chart",[{label:"Validation savings",color:"#4ade80",values:points.map(point=>point.validation_savings_vnd)}]);}}catch{}$("training-log").textContent+=`\n${event.data}`;};events.addEventListener("end",()=>{events.close();loadTraining();});}catch(error){$("training-log").textContent=error.message;}});

async function loadHuman(){const payload=await api("/api/brain-env/context");$("human-day").innerHTML=payload.days.map(day=>`<option value="${day.day_index}">${day.date_iso||`Day ${day.day_index}`}</option>`).join("");}
$("human-action").addEventListener("input",()=>$("human-action-value").textContent=Number($("human-action").value).toFixed(2));
$("human-start").addEventListener("click",async()=>{try{const payload=await api("/api/brain-env/sessions",{method:"POST",body:JSON.stringify({day_index:Number($("human-day").value),starting_peak_kw:Number($("human-peak").value)})});state.human=payload.status;state.humanTrace=[];renderHuman();}catch(error){$("human-status").textContent=error.message;}});
$("human-step").addEventListener("click",async()=>{if(!state.human)return;try{const payload=await api(`/api/brain-env/sessions/${state.human.session_id}/step`,{method:"POST",body:JSON.stringify({action:Number($("human-action").value)})});state.human=payload.status;state.humanTrace.push(payload.entry);renderHuman();}catch(error){$("human-status").textContent=error.message;}});
$("human-reset").addEventListener("click",async()=>{if(state.human)await api(`/api/brain-env/sessions/${state.human.session_id}`,{method:"DELETE"}).catch(()=>{});state.human=null;state.humanTrace=[];renderHuman();});
function renderHuman(){const summary=state.human?.summary||{};metrics($("human-summary"),[["Step",state.human?`${state.human.step_index}/${state.human.total_steps}`:"0"],["SOC",number((summary.state_of_charge||0)*100)+"%"],["BESS peak",number(summary.bess_monthly_peak_kw)+" kW"],["Raw peak",number(summary.raw_monthly_peak_kw)+" kW"],["Savings",number(summary.net_battery_savings_vnd,0)+" VND"]]);plot("human-chart",[{label:"BESS grid",color:"#38bdf8",values:state.humanTrace.map(row=>row.bess_grid_import_kw)},{label:"Raw grid",color:"#94aebe",values:state.humanTrace.map(row=>row.raw_grid_import_kw)},{label:"Battery kW",color:"#a78bfa",values:state.humanTrace.map(row=>row.final_battery_kw)}]);$("human-status").textContent=state.human?JSON.stringify(state.human,null,2):"Start a day to enter the twin worlds.";}

async function loadControllers(){const payload=await api("/api/dispatch/policies");state.controllers=payload.controllers;roster($("dispatch-roster"),state.controllers,"dispatch");roster($("benchmark-roster"),state.controllers,"benchmark");roster($("live-roster"),state.controllers,"live");roster($("shadow-roster"),state.controllers,"shadow");}
$("dispatch-run").addEventListener("click",async()=>{try{$("dispatch-status").textContent="Running independent BrainEnv worlds...";const payload=await api("/api/dispatch/run",{method:"POST",body:JSON.stringify({controllers:selected("dispatch")})});state.dispatch=payload.controllers;renderDispatch();$("dispatch-status").textContent=payload.warnings.join("\n")||`Saved run ${payload.run_id}`;}catch(error){$("dispatch-status").textContent=error.message;}});
function dayKeys(results){const source=Object.values(results||{})[0]?.trace||[];return source.reduce((out,row)=>{const key=`${row.day_index}|${row.date_iso||""}`;if(!out.some(item=>item.key===key))out.push({key,day_index:row.day_index,date_iso:row.date_iso});return out;},[]);}
function renderDispatch(){const keys=dayKeys(state.dispatch);$("dispatch-day").innerHTML=keys.map((row,index)=>`<option value="${index}">${row.date_iso||`Day ${row.day_index}`}</option>`).join("");metrics($("dispatch-kpis"),Object.entries(state.dispatch||{}).map(([id,result])=>[result.meta.display_name||id,`${number(result.kpi.savings_vnd,0)} VND saved`]));drawDispatch();}
function drawDispatch(){const keys=dayKeys(state.dispatch),key=keys[Number($("dispatch-day").value||0)];if(!key)return;const series=[{label:"Raw grid",color:"#94aebe",values:Object.values(state.dispatch)[0].trace.filter(row=>row.day_index===key.day_index&&row.date_iso===key.date_iso).map(row=>row.raw_grid_import_kw)}],colors=["#38bdf8","#4ade80","#a78bfa","#fb923c"];Object.entries(state.dispatch).forEach(([id,result],index)=>series.push({label:result.meta.display_name||id,color:colors[index%colors.length],values:result.trace.filter(row=>row.day_index===key.day_index&&row.date_iso===key.date_iso).map(row=>row.grid_import_kw)}));plot("dispatch-chart",series);}
$("dispatch-day").addEventListener("change",drawDispatch);

$("benchmark-run").addEventListener("click",async()=>{try{const job=await api("/api/benchmarking/jobs",{method:"POST",body:JSON.stringify({controllers:selected("benchmark")})});state.benchmarkJob=job.id;pollBenchmark();}catch(error){$("benchmark-status").textContent=error.message;}});
async function pollBenchmark(){if(!state.benchmarkJob)return;const job=await api(`/api/benchmarking/jobs/${state.benchmarkJob}`);$("benchmark-status").textContent=`${job.stage} ${job.completed}/${job.total}`;if(job.status==="complete"){const result=await api(`/api/benchmarking/runs/${job.run_id}`);table($("benchmark-result"),result.leaderboard,[["display_name","Brain"],["bess_cost_vnd","BESS cost",number],["savings_vnd","Savings",number],["bess_peak_kw","Peak kW",number],["ending_soc_compliant","Final SOC"]]);return;}if(["failed","cancelled"].includes(job.status)){$("benchmark-status").textContent+=` ${job.error||""}`;return;}setTimeout(pollBenchmark,750);}

$("live-create").addEventListener("click",async()=>{try{state.live=await api("/api/live-runs",{method:"POST",body:JSON.stringify({controllers:selected("live")})});renderLive();}catch(error){$("live-status").textContent=error.message;}});
$("live-step").addEventListener("click",async()=>{if(!state.live)return;try{const payload=await api(`/api/live-runs/${state.live.id}/step`,{method:"POST",body:"{}"});state.live=payload.session;renderLive();}catch(error){$("live-status").textContent=error.message;}});
function renderLive(){const day=state.live?.days?.at(-1);metrics($("live-summary"),[["Day",state.live?`${state.live.cursor}/${state.live.total_days}`:"0"],["Controllers",state.live?.controller_ids?.length||0],["Complete",state.live?.complete?"yes":"no"]]);if(day){const colors=["#38bdf8","#4ade80","#a78bfa"];plot("live-chart",Object.entries(day.controllers).map(([id,result],index)=>({label:result.meta.display_name||id,color:colors[index%colors.length],values:result.trace.map(row=>row.grid_import_kw)})));}$("live-status").textContent=state.live?JSON.stringify({id:state.live.id,warnings:state.live.warnings},null,2):"Create a session to begin.";}

async function loadShadow(){const config=await api("/api/shadow/config");$("shadow-source-kind").value=config.source_kind;$("shadow-source").value=config.source;config.controllers?.forEach(id=>{const input=document.querySelector(`[data-roster="shadow"][value="${CSS.escape(id)}"]`);if(input)input.checked=true;});await renderShadowMonthly();}
$("shadow-save").addEventListener("click",async()=>{try{await api("/api/shadow/config",{method:"POST",body:JSON.stringify({source_kind:$("shadow-source-kind").value,source:$("shadow-source").value,controllers:selected("shadow"),parameters:state.parameters})});$("shadow-status").textContent="Shadow configuration frozen.";}catch(error){$("shadow-status").textContent=error.message;}});
$("shadow-run").addEventListener("click",async()=>{try{const job=await api("/api/shadow/catchup",{method:"POST",body:JSON.stringify({start_date:$("shadow-start").value,end_date:$("shadow-end").value})});state.shadowJob=job.id;pollShadow();}catch(error){$("shadow-status").textContent=error.message;}});
async function pollShadow(){const job=await api(`/api/shadow/jobs/${state.shadowJob}`);$("shadow-status").textContent=`${job.stage} ${job.completed}/${job.total}`;if(job.status==="complete"){await renderShadowMonthly();return;}if(["failed","cancelled"].includes(job.status)){$("shadow-status").textContent+=` ${job.error||""}`;return;}setTimeout(pollShadow,750);}
async function renderShadowMonthly(){const payload=await api("/api/shadow/monthly");const rows=payload.months.flatMap(month=>Object.entries(month.controllers).map(([id,value])=>({month:month.month,controller:id,...value})));table($("shadow-monthly"),rows,[["month","Month"],["controller","Brain"],["energy_cost_vnd","Energy",number],["demand_cost_vnd","Demand",number],["wear_cost_vnd","Wear",number],["savings_vnd","Savings",number]]);}
$("shadow-reset").addEventListener("click",async()=>{if(!confirm("Delete all persistent shadow history?"))return;await api("/api/shadow/reset",{method:"POST",body:"{}"});$("shadow-status").textContent="Shadow history deleted. This cannot be recovered.";renderShadowMonthly();});
$("shadow-connector-test").addEventListener("click",async()=>{try{$("shadow-connector-status").textContent=JSON.stringify(await api("/api/shadow/connector/test",{method:"POST",body:"{}"}),null,2);}catch(error){$("shadow-connector-status").textContent=error.message;}});

async function init(){await Promise.all([loadSizing(),loadTraining(),loadHuman(),loadControllers()]);await loadShadow();}
init().catch(error=>console.error(error));
window.addEventListener("resize",()=>{drawSizing();drawDispatch();renderHuman();renderLive();});
