"use strict";

const state={parameters:window.BRAIN_HQ_INITIAL,sizing:null,oracle:null,controllers:[],dispatch:null,human:null,humanTrace:[],live:null,benchmarkJob:null,shadowJob:null,shadowDays:[],chartVisibility:{}};
const $=id=>document.getElementById(id);
const number=(value,digits=2)=>Number(value||0).toLocaleString(undefined,{maximumFractionDigits:digits});
async function api(url,options={}){const response=await fetch(url,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||`${response.status} ${response.statusText}`);return payload;}
function formObject(form){return Object.fromEntries([...new FormData(form).entries()].map(([key,value])=>[key,value]));}
function metrics(target,rows){target.innerHTML=rows.map(([label,value])=>`<div class="metric"><span>${label}</span><b>${value}</b></div>`).join("");}
function table(target,rows,columns){if(!rows.length){target.innerHTML="<p>No rows yet.</p>";return;}target.innerHTML=`<table><thead><tr>${columns.map(column=>`<th>${column[1]}</th>`).join("")}</tr></thead><tbody>${rows.map(row=>`<tr>${columns.map(column=>`<td>${column[2]?column[2](row[column[0]],row):row[column[0]]??""}</td>`).join("")}</tr>`).join("")}</tbody></table>`;}
function roster(target,controllers,prefix,defaults=["brain1","brain2"]){target.innerHTML=controllers.filter(row=>!row.error).map(row=>`<label><input type="checkbox" data-roster="${prefix}" value="${row.id}" ${defaults.includes(row.id)?"checked":""}>${row.display_name||row.name}</label>`).join("");}
function selected(prefix){return [...document.querySelectorAll(`[data-roster="${prefix}"]:checked`)].map(input=>input.value);}
function canvasContext(id){const canvas=$(id);const ratio=devicePixelRatio||1;const width=Math.max(320,canvas.clientWidth);const height=Math.max(220,canvas.clientHeight);canvas.width=width*ratio;canvas.height=height*ratio;const context=canvas.getContext("2d");context.setTransform(ratio,0,0,ratio,0,0);context.clearRect(0,0,width,height);return{context,width,height};}
function bindChartHover(id,series,labels,pad,width,count,unit){const canvas=$(id);canvas._brainChart={series,labels,pad,width,count,unit};if(canvas.dataset.hoverBound)return;canvas.dataset.hoverBound="1";const readout=document.createElement("div");readout.className="chart-readout";readout.style.position="fixed";readout.style.zIndex="50";document.body.append(readout);canvas._brainReadout=readout;canvas.addEventListener("mousemove",event=>{const model=canvas._brainChart,rect=canvas.getBoundingClientRect(),x=event.clientX-rect.left,index=Math.max(0,Math.min(model.count-1,Math.round((x-model.pad.left)*(model.count-1)/(model.width-model.pad.left-model.pad.right))));const label=model.labels[index]||`Sample ${index+1}`,rows=model.series.map(row=>`${row.label}: ${number(row.values[index])}${model.unit?` ${model.unit}`:""}`);readout.textContent=[label,...rows].join("\n");readout.style.display="block";readout.style.left=`${Math.max(8,Math.min(event.clientX+14,window.innerWidth-280))}px`;readout.style.top=`${Math.max(8,Math.min(event.clientY+14,window.innerHeight-Math.max(80,readout.offsetHeight)-8))}px`;});canvas.addEventListener("mouseleave",()=>{readout.style.display="none";});}
function plot(id,series,options={}){const {context,width,height}=canvasContext(id);const pad={left:64,right:18,top:18,bottom:34};const values=series.flatMap(row=>row.values).filter(Number.isFinite);if(!values.length){context.fillStyle="#94aebe";context.fillText("Enable a line to inspect this trace",20,30);const readout=$(id).parentElement.querySelector(".chart-readout");if(readout)readout.style.display="none";return;}let low=Math.min(...values),high=Math.max(...values);if(options.includeZero!==false){low=Math.min(0,low);high=Math.max(0,high);}if(options.minimum!==undefined)low=options.minimum;if(options.maximum!==undefined)high=options.maximum;const span=Math.max(1e-9,high-low),count=Math.max(...series.map(row=>row.values.length),2);context.font="11px Segoe UI";context.strokeStyle="#294258";context.fillStyle="#94aebe";for(let i=0;i<=4;i++){const value=high-span*i/4,y=pad.top+(height-pad.top-pad.bottom)*i/4;context.beginPath();context.moveTo(pad.left,y);context.lineTo(width-pad.right,y);context.stroke();context.fillText(number(value,Math.abs(value)<10?2:0),4,y+4);}if(low<0&&high>0){const zeroY=pad.top+(height-pad.top-pad.bottom)*(high/span);context.strokeStyle="#60788a";context.beginPath();context.moveTo(pad.left,zeroY);context.lineTo(width-pad.right,zeroY);context.stroke();}series.forEach(row=>{context.save();context.strokeStyle=row.color;context.lineWidth=row.width||2;context.globalAlpha=row.opacity??1;context.setLineDash(row.dash||[]);context.beginPath();row.values.forEach((value,index)=>{if(!Number.isFinite(value))return;const x=pad.left+(width-pad.left-pad.right)*index/(count-1),y=pad.top+(height-pad.top-pad.bottom)*(1-(value-low)/span);index?context.lineTo(x,y):context.moveTo(x,y);});context.stroke();context.restore();});context.fillStyle="#94aebe";context.fillText(options.unit||"",4,12);const labels=options.labels||[];if(labels.length){context.fillText(labels[0]||"",pad.left,height-8);const end=String(labels.at(-1)||"");context.fillText(end,width-pad.right-context.measureText(end).width,height-8);}bindChartHover(id,series,labels,pad,width,count,options.unit||"");}
function controlledPlot(controlId,canvasId,series,options,redraw){const target=$(controlId);if(!target){plot(canvasId,series,options);return;}const signature=series.map(row=>`${row.key}:${row.label}`).join("|");if(target.dataset.signature!==signature){target.dataset.signature=signature;target.innerHTML=series.map(row=>{const stateKey=`${controlId}:${row.key}`,checked=state.chartVisibility[stateKey]??row.defaultVisible!==false;state.chartVisibility[stateKey]=checked;return `<label class="line-toggle ${checked?"active":""}"><input type="checkbox" data-line-key="${stateKey}" ${checked?"checked":""}><i style="--line-color:${row.color};--line-dash:${row.dash?.length?"dashed":"solid"}"></i><span>${row.label}</span></label>`;}).join("");target.querySelectorAll("input").forEach(input=>input.addEventListener("change",()=>{state.chartVisibility[input.dataset.lineKey]=input.checked;input.closest("label").classList.toggle("active",input.checked);redraw();}));}const visible=series.filter(row=>state.chartVisibility[`${controlId}:${row.key}`]!==false);plot(canvasId,visible,options);}

document.querySelectorAll(".tab").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".tab,.panel").forEach(item=>item.classList.remove("active"));button.classList.add("active");$(`tab-${button.dataset.tab}`).classList.add("active");}));

function oracleDayFor(day){return state.oracle?.days?.find(row=>row.solved&&(row.day_index===day.day_index||row.date_iso&&row.date_iso===day.date_iso));}
function renderOracleStatus(){const output=$("oracle-output"),summary=state.oracle?.summary;if(!state.oracle){output.textContent="No compatible cached Oracle yet. Calculate once to add the ceiling lines.";return;}if(state.oracle.available===false){output.textContent=state.oracle.reason||state.oracle.status||"Oracle is unavailable for this dataset.";return;}output.textContent=`Oracle ready · ${state.oracle.days?.filter(day=>day.solved).length||0} solved days · ${number(summary?.oracle_saving_vnd,0)} VND ceiling savings`;}
async function loadSizing(){const payload=await api("/api/sizing");state.sizing=payload.benchmark;state.oracle=payload.oracle||null;const summary=state.sizing.summary;metrics($("sizing-summary"),[["Days",summary.day_count],["Raw grid kWh",number(summary.total_grid_kWh)],["Raw peak kW",number(summary.peak_grid_kW)],["Energy cost",number(summary.energy_cost_vnd,0)+" VND"],["Demand cost",number(summary.demand_charge_vnd,0)+" VND"]]);$("sizing-day").innerHTML=state.sizing.days.map((day,index)=>`<option value="${index}">${day.date_iso||`Day ${day.day_index}`}</option>`).join("");renderOracleStatus();drawSizing();}
function drawSizing(){const day=state.sizing?.days?.[Number($("sizing-day").value||0)];if(!day)return;const peak=day.peak_grid_kW,oracle=oracleDayFor(day),series=[{key:"load",label:"Factory load",color:"#fb923c",values:day.load},{key:"pv",label:"PV",color:"#4ade80",values:day.pv},{key:"grid",label:"Raw grid",color:"#38bdf8",values:day.grid},{key:"meter",label:"Raw 30-minute meter",color:"#facc15",dash:[3,4],values:day.rolling_grid,defaultVisible:false},{key:"peak",label:`Raw day peak ${number(peak)} kW`,color:"#fb7185",dash:[8,5],values:day.grid.map(()=>peak)}];if(oracle){const oraclePeak=oracle.month_peak?.value_kW??oracle.peak_grid_kW;series.push({key:"oracle-grid",label:"Oracle grid",color:"#f472b6",width:3,values:oracle.grid},{key:"oracle-meter",label:"Oracle 30-minute meter",color:"#c084fc",dash:[3,4],values:oracle.rolling_grid,defaultVisible:false},{key:"oracle-peak",label:`Oracle billing peak ${number(oraclePeak)} kW`,color:"#e879f9",dash:[10,5],values:oracle.grid.map(()=>oraclePeak)});}controlledPlot("sizing-lines","sizing-chart",series,{unit:"kW",labels:state.sizing.time_labels},drawSizing);}
$("sizing-day").addEventListener("change",drawSizing);
$("save-settings").addEventListener("click",async()=>{try{const payload=formObject($("settings-form"));payload.billing_sunday=$("settings-form").elements.billing_sunday.checked;const result=await api("/api/parameters",{method:"POST",body:JSON.stringify(payload)});state.parameters=result.parameters;await loadSizing();}catch(error){alert(error.message);}});
$("oracle-run").addEventListener("click",async()=>{try{$("oracle-output").textContent="Solving optional ceiling...";const payload=await api("/candidate-oracle/0?force=1");state.oracle=payload.candidate.oracle;renderOracleStatus();drawSizing();drawDispatch();}catch(error){$("oracle-output").textContent=error.message;}});

async function loadTraining(){const [datasets,checkpoints]=await Promise.all([api("/api/training/datasets"),api("/api/training/checkpoints")]);$("training-dataset").innerHTML=datasets.filter(row=>row.status==="ok").map(row=>`<option value="${row.id}">${row.source} (${row.n_days} days, ${row.res_min}m)</option>`).join("");$("training-resume").innerHTML='<option value="">Fresh run</option>'+checkpoints.resume.map(name=>`<option>${name}</option>`).join("");table($("training-checkpoints"),checkpoints.deployments,[["display_name","Checkpoint"],["algo","Algorithm"],["error","Status",value=>value||"ready"]]);}
$("training-refresh").addEventListener("click",loadTraining);
$("training-start").addEventListener("click",async()=>{try{const result=await api("/api/training/start",{method:"POST",body:JSON.stringify(formObject($("training-form")))});$("training-log").textContent=`Job ${result.job_id} launched. Heavy training belongs on the configured machine.`;const points=[],events=new EventSource(`/api/training/jobs/${result.job_id}/events`);events.onmessage=event=>{try{const row=JSON.parse(event.data);if(row.type==="validation"){points.push(row);plot("training-chart",[{label:"Validation savings",color:"#4ade80",values:points.map(point=>point.validation_savings_vnd)}]);}}catch{}$("training-log").textContent+=`\n${event.data}`;};events.addEventListener("end",()=>{events.close();loadTraining();});}catch(error){$("training-log").textContent=error.message;}});

async function loadHuman(){const payload=await api("/api/brain-env/context");$("human-day").innerHTML=payload.days.map(day=>`<option value="${day.day_index}">${day.date_iso||`Day ${day.day_index}`}</option>`).join("");}
$("human-action").addEventListener("input",()=>$("human-action-value").textContent=Number($("human-action").value).toFixed(2));
$("human-start").addEventListener("click",async()=>{try{const payload=await api("/api/brain-env/sessions",{method:"POST",body:JSON.stringify({day_index:Number($("human-day").value),starting_peak_kw:Number($("human-peak").value)})});state.human=payload.status;state.humanTrace=[];renderHuman();}catch(error){$("human-status").textContent=error.message;}});
$("human-step").addEventListener("click",async()=>{if(!state.human)return;try{const payload=await api(`/api/brain-env/sessions/${state.human.session_id}/step`,{method:"POST",body:JSON.stringify({action:Number($("human-action").value)})});state.human=payload.status;state.humanTrace.push(payload.entry);renderHuman();}catch(error){$("human-status").textContent=error.message;}});
$("human-reset").addEventListener("click",async()=>{if(state.human)await api(`/api/brain-env/sessions/${state.human.session_id}`,{method:"DELETE"}).catch(()=>{});state.human=null;state.humanTrace=[];renderHuman();});
function renderHuman(){const summary=state.human?.summary||{},rows=state.humanTrace,labels=rows.map(row=>row.time);metrics($("human-summary"),[["Step",state.human?`${state.human.step_index}/${state.human.total_steps}`:"0"],["SOC",number((summary.state_of_charge||0)*100)+"%"],["BESS peak",number(summary.bess_monthly_peak_kw)+" kW"],["Raw peak",number(summary.raw_monthly_peak_kw)+" kW"],["Savings",number(summary.net_battery_savings_vnd,0)+" VND"]]);controlledPlot("human-lines","human-chart",[{key:"load",label:"Load",color:"#fb923c",values:rows.map(row=>row.load_kw)},{key:"pv",label:"PV",color:"#4ade80",values:rows.map(row=>row.pv_kw),defaultVisible:false},{key:"bess-grid",label:"BESS grid",color:"#38bdf8",values:rows.map(row=>row.bess_grid_import_kw)},{key:"raw-grid",label:"Raw grid",color:"#94aebe",values:rows.map(row=>row.raw_grid_import_kw)},{key:"battery",label:"Executed battery",color:"#a78bfa",values:rows.map(row=>row.final_battery_kw)},{key:"bess-peak",label:"BESS meter peak",color:"#facc15",dash:[8,5],values:rows.map(row=>row.bess_monthly_peak_kw)},{key:"raw-peak",label:"Raw meter peak",color:"#fb7185",dash:[3,4],values:rows.map(row=>row.raw_monthly_peak_kw)}],{unit:"kW",labels},renderHuman);const last=rows.at(-1);$("human-status").textContent=state.human?`Step ${state.human.step_index}/${state.human.total_steps}${last?` · requested ${number(last.requested_battery_kw)} kW · executed ${number(last.final_battery_kw)} kW`:""}`:"Start a day to enter the twin worlds.";}

async function loadControllers(){const payload=await api("/api/dispatch/policies");state.controllers=payload.controllers;roster($("dispatch-roster"),state.controllers,"dispatch");roster($("benchmark-roster"),state.controllers,"benchmark");roster($("live-roster"),state.controllers,"live");roster($("shadow-roster"),state.controllers,"shadow");}
$("dispatch-run").addEventListener("click",async()=>{try{$("dispatch-status").textContent="Running independent BrainEnv worlds...";const payload=await api("/api/dispatch/run",{method:"POST",body:JSON.stringify({controllers:selected("dispatch")})});state.dispatch=payload.controllers;renderDispatch();$("dispatch-status").textContent=payload.warnings.join("\n")||`Saved run ${payload.run_id}`;}catch(error){$("dispatch-status").textContent=error.message;}});
function dayKeys(results){const source=Object.values(results||{})[0]?.trace||[];return source.reduce((out,row)=>{const key=`${row.day_index}|${row.date_iso||""}`;if(!out.some(item=>item.key===key))out.push({key,day_index:row.day_index,date_iso:row.date_iso});return out;},[]);}
const brainColors=["#38bdf8","#4ade80","#a78bfa","#fb923c","#f472b6","#22d3ee"];
function renderDispatch(){const keys=dayKeys(state.dispatch),current=$("dispatch-day").value;$("dispatch-day").innerHTML=keys.map((row,index)=>`<option value="${index}">${row.date_iso||`Day ${row.day_index}`}</option>`).join("");if(current&&Number(current)<keys.length)$("dispatch-day").value=current;const entries=Object.entries(state.dispatch||{}),savings=entries.map(([,result])=>result.kpi.savings_vnd),peaks=entries.map(([,result])=>result.kpi.bess_peak_kw);metrics($("dispatch-kpis"),[["Brains",entries.length],["Best savings",number(savings.length?Math.max(...savings):0,0)+" VND"],["Lowest peak",number(peaks.length?Math.min(...peaks):0)+" kW"],["Raw peak",number(entries[0]?.[1]?.kpi.raw_peak_kw)+" kW"],["Adjusted actions",number(entries.reduce((sum,[,result])=>sum+result.kpi.action_adjustments,0),0)]]);table($("dispatch-scorecard"),entries.map(([id,result])=>({brain:result.meta.display_name||id,...result.kpi})),[["brain","Brain"],["raw_cost_vnd","Raw bill",value=>number(value,0)],["bess_cost_vnd","BESS bill",value=>number(value,0)],["savings_vnd","Savings",value=>number(value,0)],["savings_pct","Savings %",value=>number(value)+"%"],["raw_peak_kw","Raw peak",value=>number(value)],["bess_peak_kw","BESS peak",value=>number(value)],["wear_cost_vnd","Wear",value=>number(value,0)],["throughput_kwh","Throughput",value=>number(value)],["action_adjustments","Adjusted",value=>number(value,0)],["ending_soc","End SOC",value=>number(value*100)+"%"]]);drawDispatch();}
function dispatchRows(result,key){return result.trace.filter(row=>row.day_index===key.day_index&&row.date_iso===key.date_iso);}
function drawDispatch(){
  const keys=dayKeys(state.dispatch),key=keys[Number($("dispatch-day").value||0)],entries=Object.entries(state.dispatch||{});
  if(!key||!entries.length)return;
  const firstRows=dispatchRows(entries[0][1],key),labels=firstRows.map(row=>row.time),power=[{key:"load",label:"Factory load",color:"#fb923c",values:firstRows.map(row=>row.load_kw)},{key:"pv",label:"PV",color:"#22c55e",values:firstRows.map(row=>row.pv_kw),defaultVisible:false},{key:"net",label:"Net load",color:"#facc15",values:firstRows.map(row=>row.net_load_kw),defaultVisible:false},{key:"raw-grid",label:"Raw grid",color:"#94aebe",width:3,values:firstRows.map(row=>row.raw_grid_import_kw)},{key:"raw-running-peak",label:"Raw running peak",color:"#fb7185",dash:[3,4],values:firstRows.map(row=>row.raw_meter_peak_kw),defaultVisible:false},{key:"raw-final-peak",label:`Raw billing-scope peak ${number(entries[0][1].kpi.raw_peak_kw)} kW`,color:"#ef4444",dash:[10,5],values:firstRows.map(()=>entries[0][1].kpi.raw_peak_kw)}],actions=[],soc=[],money=[];
  const oracle=oracleDayFor(key);
  if(oracle){
    const oraclePeak=oracle.month_peak?.value_kW??oracle.peak_grid_kW;
    power.push({key:"oracle-grid",label:"Oracle grid",color:"#f472b6",width:3,values:oracle.grid},{key:"oracle-meter",label:"Oracle 30-minute meter",color:"#c084fc",dash:[3,4],values:oracle.rolling_grid,defaultVisible:false},{key:"oracle-peak",label:`Oracle billing peak ${number(oraclePeak)} kW`,color:"#e879f9",dash:[10,5],values:oracle.grid.map(()=>oraclePeak)});
    actions.push({key:"oracle-battery",label:"Oracle battery schedule",color:"#f472b6",width:3,values:oracle.discharge.map((value,index)=>value-(oracle.grid_charge[index]||0)-(oracle.solar_charge[index]||0))});
    soc.push({key:"oracle-soc",label:"Oracle SOC",color:"#f472b6",width:3,values:oracle.soc});
  }
  entries.forEach(([id,result],index)=>{const rows=dispatchRows(result,key),color=brainColors[index%brainColors.length],name=result.meta.display_name||id;power.push({key:`${id}-grid`,label:`${name} grid`,color,width:3,values:rows.map(row=>row.grid_import_kw)},{key:`${id}-running-peak`,label:`${name} running peak`,color,dash:[3,4],opacity:.75,values:rows.map(row=>row.meter_peak_kw),defaultVisible:false},{key:`${id}-final-peak`,label:`${name} billing-scope peak ${number(result.kpi.bess_peak_kw)} kW`,color,dash:[10,5],values:rows.map(()=>result.kpi.bess_peak_kw)});actions.push({key:`${id}-requested`,label:`${name} requested`,color,dash:[3,4],values:rows.map(row=>row.requested_battery_kw),defaultVisible:false},{key:`${id}-projected`,label:`${name} projected`,color,dash:[9,4],values:rows.map(row=>row.projected_battery_kw),defaultVisible:false},{key:`${id}-executed`,label:`${name} executed`,color,width:3,values:rows.map(row=>row.executed_battery_kw)});soc.push({key:`${id}-soc`,label:`${name} SOC`,color,width:3,values:rows.map(row=>row.soc_after*100)});money.push({key:`${id}-reward`,label:`${name} timestep reward`,color,dash:[3,4],values:rows.map(row=>row.reward_vnd),defaultVisible:false},{key:`${id}-cumulative`,label:`${name} cumulative savings`,color,width:3,values:rows.map(row=>row.cumulative_savings_vnd)});});
  const finalSoc=Number(state.parameters.required_final_soc||0)*100;soc.push({key:"required-final",label:`Required final SOC ${number(finalSoc)}%`,color:"#facc15",dash:[10,5],values:firstRows.map(()=>finalSoc)});controlledPlot("dispatch-power-lines","dispatch-chart",power,{unit:"kW",labels},drawDispatch);controlledPlot("dispatch-action-lines","dispatch-action-chart",actions,{unit:"battery kW",labels},drawDispatch);controlledPlot("dispatch-soc-lines","dispatch-soc-chart",soc,{unit:"SOC %",labels,minimum:0,maximum:100},drawDispatch);controlledPlot("dispatch-money-lines","dispatch-money-chart",money,{unit:"VND",labels},drawDispatch);
}
$("dispatch-day").addEventListener("change",drawDispatch);

$("benchmark-run").addEventListener("click",async()=>{try{const job=await api("/api/benchmarking/jobs",{method:"POST",body:JSON.stringify({controllers:selected("benchmark")})});state.benchmarkJob=job.id;pollBenchmark();}catch(error){$("benchmark-status").textContent=error.message;}});
async function pollBenchmark(){if(!state.benchmarkJob)return;const job=await api(`/api/benchmarking/jobs/${state.benchmarkJob}`);$("benchmark-status").textContent=`${job.stage} ${job.completed}/${job.total}`;if(job.status==="complete"){const result=await api(`/api/benchmarking/runs/${job.run_id}`);table($("benchmark-result"),result.leaderboard,[["display_name","Brain"],["bess_cost_vnd","BESS cost",number],["savings_vnd","Savings",number],["bess_peak_kw","Peak kW",number],["ending_soc_compliant","Final SOC"]]);return;}if(["failed","cancelled"].includes(job.status)){$("benchmark-status").textContent+=` ${job.error||""}`;return;}setTimeout(pollBenchmark,750);}

$("live-create").addEventListener("click",async()=>{try{state.live=await api("/api/live-runs",{method:"POST",body:JSON.stringify({controllers:selected("live")})});renderLive();}catch(error){$("live-status").textContent=error.message;}});
$("live-step").addEventListener("click",async()=>{if(!state.live)return;try{const payload=await api(`/api/live-runs/${state.live.id}/step`,{method:"POST",body:"{}"});state.live=payload.session;renderLive();}catch(error){$("live-status").textContent=error.message;}});
function renderLive(){const days=state.live?.days||[],daySelect=$("live-day"),oldCount=Number(daySelect.dataset.count||0),current=daySelect.value;daySelect.innerHTML=days.map((day,index)=>`<option value="${index}">${day.date||`Day ${day.day_index}`}</option>`).join("");if(days.length!==oldCount){daySelect.value=String(Math.max(0,days.length-1));daySelect.dataset.count=String(days.length);}else if(current&&Number(current)<days.length){daySelect.value=current;}const day=days[Number(daySelect.value||0)];metrics($("live-summary"),[["Day",state.live?`${state.live.cursor}/${state.live.total_days}`:"0"],["Controllers",state.live?.controller_ids?.length||0],["Complete",state.live?.complete?"yes":"no"]]);if(day){const entries=Object.entries(day.controllers),first=entries[0]?.[1]?.trace||[],series=[{key:"raw-grid",label:"Raw grid",color:"#94aebe",width:3,values:first.map(row=>row.raw_grid_import_kw)},{key:"raw-peak",label:"Raw meter peak",color:"#fb7185",dash:[8,5],values:first.map(row=>row.raw_meter_peak_kw)}];entries.forEach(([id,result],index)=>{const color=brainColors[index%brainColors.length],name=result.meta.display_name||id;series.push({key:`${id}-grid`,label:`${name} grid`,color,width:3,values:result.trace.map(row=>row.grid_import_kw)},{key:`${id}-peak`,label:`${name} meter peak`,color,dash:[8,5],values:result.trace.map(row=>row.meter_peak_kw),defaultVisible:false},{key:`${id}-battery`,label:`${name} battery`,color,dash:[3,4],values:result.trace.map(row=>row.executed_battery_kw),defaultVisible:false});});controlledPlot("live-lines","live-chart",series,{unit:"kW",labels:first.map(row=>row.time)},renderLive);}else{plot("live-chart",[],{});}const warnings=state.live?.warnings||[];$("live-status").textContent=state.live?`Session ${state.live.id} · ${warnings.length?warnings.join(" · "):"no warnings"}`:"Create a session to begin.";}
$("live-day").addEventListener("change",renderLive);

async function loadShadow(){const config=await api("/api/shadow/config");$("shadow-source-kind").value=config.source_kind;$("shadow-source").value=config.source;config.controllers?.forEach(id=>{const input=document.querySelector(`[data-roster="shadow"][value="${CSS.escape(id)}"]`);if(input)input.checked=true;});await renderShadowMonthly();}
$("shadow-save").addEventListener("click",async()=>{try{await api("/api/shadow/config",{method:"POST",body:JSON.stringify({source_kind:$("shadow-source-kind").value,source:$("shadow-source").value,controllers:selected("shadow"),parameters:state.parameters})});$("shadow-status").textContent="Shadow configuration frozen.";}catch(error){$("shadow-status").textContent=error.message;}});
$("shadow-run").addEventListener("click",async()=>{try{const job=await api("/api/shadow/catchup",{method:"POST",body:JSON.stringify({start_date:$("shadow-start").value,end_date:$("shadow-end").value})});state.shadowJob=job.id;pollShadow();}catch(error){$("shadow-status").textContent=error.message;}});
async function pollShadow(){const job=await api(`/api/shadow/jobs/${state.shadowJob}`);$("shadow-status").textContent=`${job.stage} ${job.completed}/${job.total}`;if(job.status==="complete"){await renderShadowMonthly();return;}if(["failed","cancelled"].includes(job.status)){$("shadow-status").textContent+=` ${job.error||""}`;return;}setTimeout(pollShadow,750);}
async function renderShadowMonthly(){const [payload,tracePayload]=await Promise.all([api("/api/shadow/monthly"),api("/api/shadow/days")]);const rows=payload.months.flatMap(month=>Object.entries(month.controllers).map(([id,value])=>({month:month.month,controller:id,...value})));table($("shadow-monthly"),rows,[["month","Month"],["controller","Brain"],["energy_cost_vnd","Energy",number],["demand_cost_vnd","Demand",number],["wear_cost_vnd","Wear",number],["savings_vnd","Savings",number]]);state.shadowDays=tracePayload.days||[];const select=$("shadow-day"),current=select.value;select.innerHTML=state.shadowDays.map((day,index)=>`<option value="${index}">${day.date||`Day ${day.day_index}`}</option>`).join("");if(current&&Number(current)<state.shadowDays.length)select.value=current;drawShadow();}
function drawShadow(){const day=state.shadowDays[Number($("shadow-day").value||0)];if(!day){plot("shadow-chart",[],{});return;}const entries=Object.entries(day.controllers||{}),first=entries[0]?.[1]||[],series=[{key:"raw-grid",label:"Raw grid",color:"#94aebe",width:3,values:first.map(row=>row.raw_grid_import_kw)},{key:"raw-peak",label:"Raw running peak",color:"#fb7185",dash:[8,5],values:first.map(row=>row.raw_meter_peak_kw)}];entries.forEach(([id,rows],index)=>{const color=brainColors[index%brainColors.length],name=state.controllers.find(row=>row.id===id)?.display_name||id,endingPeak=rows.at(-1)?.meter_peak_kw||0;series.push({key:`${id}-grid`,label:`${name} grid`,color,width:3,values:rows.map(row=>row.grid_import_kw)},{key:`${id}-battery`,label:`${name} battery`,color,dash:[3,4],values:rows.map(row=>row.executed_battery_kw),defaultVisible:false},{key:`${id}-running-peak`,label:`${name} running peak`,color,dash:[3,4],values:rows.map(row=>row.meter_peak_kw),defaultVisible:false},{key:`${id}-ending-peak`,label:`${name} ending peak ${number(endingPeak)} kW`,color,dash:[10,5],values:rows.map(()=>endingPeak)});});controlledPlot("shadow-lines","shadow-chart",series,{unit:"kW",labels:first.map(row=>row.time)},drawShadow);}
$("shadow-day").addEventListener("change",drawShadow);
$("shadow-reset").addEventListener("click",async()=>{if(!confirm("Delete all persistent shadow history?"))return;await api("/api/shadow/reset",{method:"POST",body:"{}"});$("shadow-status").textContent="Shadow history deleted. This cannot be recovered.";renderShadowMonthly();});
$("shadow-connector-test").addEventListener("click",async()=>{try{$("shadow-connector-status").textContent=JSON.stringify(await api("/api/shadow/connector/test",{method:"POST",body:"{}"}),null,2);}catch(error){$("shadow-connector-status").textContent=error.message;}});

async function init(){await Promise.all([loadSizing(),loadTraining(),loadHuman(),loadControllers()]);await loadShadow();}
init().catch(error=>console.error(error));
window.addEventListener("resize",()=>{drawSizing();drawDispatch();renderHuman();renderLive();});
